//! Stage 11b.1.a build script: compute BLAKE3 of `assets/canonical_spec.json`
//! at compile time and emit it as a `const [u8; 32]` constant the crate's
//! `shared` module includes.
//!
//! This pins the canonical spec's hash at compile time so the verifier can
//! reject any artifact whose declared `model_hash` doesn't match — without
//! relying on a runtime file read at verification time.

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set"));
    let spec_path = manifest_dir.join("assets").join("canonical_spec.json");

    // Re-run the build if the spec file changes.
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let bytes = fs::read(&spec_path)
        .unwrap_or_else(|e| panic!("read {}: {}", spec_path.display(), e));
    let hash = blake3::hash(&bytes);

    // Emit `const EXPECTED_SPEC_HASH: [u8; 32] = [..];` into OUT_DIR.
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set"));
    let out_path = out_dir.join("expected_spec_hash.rs");

    let bytes_str = hash
        .as_bytes()
        .iter()
        .map(|b| format!("0x{:02x}", b))
        .collect::<Vec<_>>()
        .join(", ");
    let content = format!(
        "// Auto-generated by build.rs from assets/canonical_spec.json.\n\
         // Re-runs only when canonical_spec.json changes.\n\
         pub const EXPECTED_SPEC_HASH: [u8; 32] = [{}];\n",
        bytes_str,
    );
    fs::write(&out_path, content).unwrap_or_else(|e| {
        panic!("write {}: {}", out_path.display(), e)
    });
}
