//! Stage 11b.1.a — shared constants and the `EXPECTED_SPEC_HASH` baked
//! at compile time from `assets/canonical_spec.json`.
//!
//! No halo2 / heavy deps in this module. Always compiled.

/// Stable identifier for the Stage 11b.1 halo2 reference backend.
/// The mainnet refusal in `omni-node`'s `verify-proof` (Stage 11b.1.b)
/// keys off this string; do NOT rename without coordinating the
/// operator-side check.
pub const BACKEND_ID: &str = "halo2-reference-mlp-v1";

/// Stable canonical-spec name + version. Recorded in every artifact's
/// `metadata.public_inputs.spec_name` / `spec_version` fields.
///
/// `CANONICAL_SPEC_VERSION` was bumped from 1 → 2 when the arithmetic
/// contract changed (truncate-toward-zero / i32 → round-half-away /
/// i64 + bias-pre-saturation). Any deserialized artifact with
/// `spec_version` not equal to this constant will fail spec-pin
/// checks in Stage 11b.1.b's verifier.
pub const CANONICAL_SPEC_NAME: &str = "halo2-mlp-v1";
pub const CANONICAL_SPEC_VERSION: u32 = 2;

/// Canonical evaluation tuple frozen in `assets/canonical_spec.json`.
/// Every framework manifest must reproduce these exact bytes via the
/// `cross_framework_equivalence` integration test.
pub const CANONICAL_INPUT: [i16; 4] = [-5, 10, 20, -100];
pub const CANONICAL_OUTPUT: [i16; 4] = [33, -32, 17, 7];

// `EXPECTED_SPEC_HASH: [u8; 32]` — BLAKE3 of
// `assets/canonical_spec.json`. Generated by `build.rs` at compile
// time and included from `$OUT_DIR/expected_spec_hash.rs`. The
// Stage 11b.1.b verifier asserts the artifact's `model_hash` matches
// this constant — the canonical spec is pinned at compile time, not
// negotiable by the artifact. (Plain comment, not a doc comment,
// because rustdoc can't attach docs to a macro invocation.)
include!(concat!(env!("OUT_DIR"), "/expected_spec_hash.rs"));

/// Stage 11c — halo2 circuit `k` (log2 number of rows in the
/// constraint system). Sized for the bounded MLP circuit with
/// the full Stage 11c gadgets: dense linear identity + RHAZ
/// (round-half-away-from-zero) gadget + saturation gadget + ReLU
/// + range checks at 8u / 15u / 16s / 16u / 17u / 23u widths.
/// Stage 11c bumped `k` from 9 → 10 to accommodate the added
/// witness rows; the preauthorized ceiling is `k = 11` (escalate
/// at `k ≥ 12`). Bumping `k` changes the committed
/// `params.bin`/`proof.bin` fixtures — treat as a frozen pin.
pub const HALO2_K: u32 = 10;
