//! Stage 11b.1.a — shared constants and the `EXPECTED_SPEC_HASH` baked
//! at compile time from `assets/canonical_spec.json`.
//!
//! No halo2 / heavy deps in this module. Always compiled.

/// Stable identifier for the Stage 11b.1 halo2 reference backend.
/// The mainnet refusal in `omni-node`'s `verify-proof` (Stage 11b.1.b)
/// keys off this string; do NOT rename without coordinating the
/// operator-side check.
pub const BACKEND_ID: &str = "halo2-reference-mlp-v1";

/// Stable canonical-spec name + version. Recorded in every artifact's
/// `metadata.public_inputs.spec_name` / `spec_version` fields.
pub const CANONICAL_SPEC_NAME: &str = "halo2-mlp-v1";
pub const CANONICAL_SPEC_VERSION: u32 = 1;

/// Canonical evaluation tuple frozen in `assets/canonical_spec.json`.
/// Every framework manifest must reproduce these exact bytes via the
/// `cross_framework_equivalence` integration test.
pub const CANONICAL_INPUT: [i16; 4] = [-5, 10, 20, -100];
pub const CANONICAL_OUTPUT: [i16; 4] = [32, -32, 17, 8];

// `EXPECTED_SPEC_HASH: [u8; 32]` — BLAKE3 of
// `assets/canonical_spec.json`. Generated by `build.rs` at compile
// time and included from `$OUT_DIR/expected_spec_hash.rs`. The
// Stage 11b.1.b verifier asserts the artifact's `model_hash` matches
// this constant — the canonical spec is pinned at compile time, not
// negotiable by the artifact. (Plain comment, not a doc comment,
// because rustdoc can't attach docs to a macro invocation.)
include!(concat!(env!("OUT_DIR"), "/expected_spec_hash.rs"));
