//! Stage 11d.2 — shared constants for the production fixed-point MLP
//! proof class.
//!
//! Distinct from `omni-proofs-halo2-reference::shared` (bounded
//! reference) per Stage 11d.0 criteria §1.6 distinguishability hard
//! rules H1/H2/H3:
//!   - H1: separate crate ⇒ separate `Halo2ProductionMlpVerifier`
//!   - H2: `EXPECTED_PRODUCTION_SPEC_HASH` ≠ reference's `EXPECTED_SPEC_HASH`
//!   - H3: distinct canonical spec at `assets/canonical_spec.json`
//!
//! No halo2 / heavy deps in this module. Always compiled.

/// Stable identifier for the Stage 11d.2 production fixed-point MLP
/// proof backend. The mainnet refusal path in `check_mainnet_eligible`
/// (layer 6) does not consult `backend_id` directly — it's recorded
/// for audit on each `AllowlistEntry` (Stage 11d.1 schema). Pinned
/// here so the const cannot drift across regeneration runs.
pub const BACKEND_ID: &str = "production-fixedpoint-mlp-v1";

/// Stable canonical-spec name + version. Recorded in artifact metadata
/// for cross-reference with the spec hash; distinct from the bounded
/// reference's `halo2-mlp-v1` to enforce hard rule H3.
pub const PRODUCTION_SPEC_NAME: &str = "production-fixedpoint-mlp-v1";
pub const PRODUCTION_SPEC_VERSION: u32 = 1;

/// Canonical input tensor pinned in `assets/canonical_spec.json`.
/// 16-dimensional i16 vector representing a deterministic small-model
/// classification input. Frozen at Stage 11d.2 commit time; the
/// `canonical_invariant_holds` test pins
/// `canonical_evaluate(CANONICAL_INPUT) == CANONICAL_OUTPUT`.
pub const CANONICAL_INPUT: [i16; 16] = [
    -5, 10, 20, -100, 7, -3, 14, 25, -8, 1, 11, -22, 4, -1, 17, 9,
];

/// Canonical output tensor pinned in `assets/canonical_spec.json`.
/// 8-dimensional i16 vector (logits over an 8-class output domain).
/// Computed via the canonical evaluator at fixture-regen time and
/// pinned here so the const drift is caught by both
/// `canonical_invariant_holds` and the cross-framework corpus tests.
///
/// **Value derived at regen time** (initial Stage 11d.2 PR fills this
/// in via the `tools/halo2_production_mlp_regen/` tool); if the spec
/// changes, both this const and the corpus.json/proof_artifact.json
/// must be regenerated together.
pub const CANONICAL_OUTPUT: [i16; 8] = [-32, -12, 6, 25, -21, -3, 16, -29];

/// Stage 11d.2 — halo2 circuit `k` (log2 number of rows). Target k=11
/// for the recommended 16 → 32 → 16 → 8 architecture. **Preauthorized
/// ceiling k ≤ 13** per Stage 11d.2 plan §13 OQ9; **halt-and-report
/// at k ≥ 14** (params.bin > 1 MB is fixture-bloat).
pub const HALO2_K: u32 = 11;

/// Stage 11d.2 — pinned `circuit_id_hex` for the production circuit.
/// Derived from `vk_canonical_bytes(&vk)` via bare BLAKE3; computed
/// by `tools/halo2_production_mlp_regen/` and pinned here so any
/// drift (e.g. a `halo2_proofs` version bump, an unintended circuit
/// edit, or a `HALO2_K` change) fails the verifier's identity
/// check loudly. **The artifact's `metadata.circuit_id_hex` MUST
/// equal this value.**
///
/// This is the layer-6 eligibility registry key (criteria §1.6 hard
/// rule H2 + Stage 11d.1 structured eligibility registry schema). The
/// future `AllowlistEntry` (Stage 11d.3) will carry the same string.
pub const EXPECTED_CIRCUIT_ID_HEX: &str =
    "593d027df3778bc582f9ec40bf453e757a1be6a9b6961243f2dfdf38fb4ea95d";

/// Stage 11d.2 — pinned `verification_key_hash_hex` for the
/// production circuit. Derived from `vk_canonical_bytes(&vk)` via
/// `mainnet_vk_hash` (= `BLAKE3("OMNINODE-VK:v1:" || vk_bytes)`,
/// criteria §1.7). Recorded here so the eventual Stage 11d.3
/// `AllowlistEntry` can reference a single pinned value; the
/// verifier's identity test enforces drift.
pub const EXPECTED_VK_HASH_HEX: &str =
    "2ec18faed223a28a23155492459c507a2672b9ff495c1df566103a19638655a9";

// `EXPECTED_PRODUCTION_SPEC_HASH: [u8; 32]` — BLAKE3 of
// `assets/canonical_spec.json`. Generated by `build.rs` at compile
// time. Distinct const name from the bounded reference's
// `EXPECTED_SPEC_HASH` to prevent any accidental cross-import.
include!(concat!(env!("OUT_DIR"), "/expected_production_spec_hash.rs"));
